Feature/te/do 779 first version
dodevops/terraform-azure-certmanager pull request #1
Opened 2021-11-10 14:01 UTC by dploeger

2021-11-11 13:16 UTC, timdeluxe requested changes

2021-11-11 13:16 UTC, timdeluxe commented on main.tf
> +# Installs and configures cert-manager
In my opinion superflous comment - i mean the module is named certmanager and the README says clearly what it is. We don't need that comment in my opinion...

2021-11-12 08:54 UTC, timdeluxe approved these changes

2021-11-15 10:12 UTC, ThomasMinor approved these changes

2021-11-15 10:29 UTC, merged